[package]
name = "Innovation-James-Guil"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies] 
actix-web = "3"
env_logger = "0.7.1"
uuid = { version = "0.6", features = ["serde", "v4"] }
